name: MasterDeploy
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.2
              with:
                  fetch-depth: '0'
            - name: Create Release folder
              run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./snwPopup
            - name: Switch to release
              run: |
                  cd snwPopup
                  ls -lsa
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.26.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DEFAULT_BUMP: 'none'
                  INITIAL_VERSION: 0.1.4

                  WITH_V: true

